### PR TITLE
Fix issues in unlink

### PR DESCRIPTION
**Pull request by StorytellerCZ**
* Fix missed underscore functionality in unlink method
* Add missing imports

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
@yubozhao BTW, I'm willing to be a maintainer.

**Comment by StorytellerCZ** [comment]
@yubozhao Any updates on merging this? Kind of need this.

**Comment by yubozhao** [comment]
hi @StorytellerCZ Yes I would love to add you on as maintainer. Let me figure out how to setup meteor publish system

**Comment by StorytellerCZ** [comment]
Thanks! Looking forward to keep this going.

**Pull request merged**
