### PR TITLE
added venmo to list of compatible accounts packages

### PR DESCRIPTION
**Pull request by pcooney10**
I updated the readme to include the accounts-venmo package

### CODE REVIEW

**Comment by yubozhao** [comment]
hey @pcooney10 

Thank you for working on the package.  I can't merge it in now just for the readme file, since this pr does not contain Meteor.linkWithVenmo func.

**Comment by pcooney10** [comment]
hey @yubozhao, wasn't sure how to add to this pull request, but here is an update that contains the `Meteor.linkWithVenmo` function: [https://github.com/yubozhao/meteor-link-accounts/pull/35](https://github.com/yubozhao/meteor-link-accounts/pull/35)

**Comment by yubozhao** [comment]
going to close this one

**Comment by pcooney10** [comment]
:ok_hand:

**Pull request closed without merging**
